In [1]:
import torch
import pandas as pd
import numpy as np

from model import DSCNet
from post_clustering import spectral_clustering

In [2]:
NUM_SAMPLES = 1320
SEQUENCE_LENGTH = 1000

In [3]:
model = DSCNet(num_samples=NUM_SAMPLES, sequence_length=SEQUENCE_LENGTH, hidden_sizes=[3, 3, 5], )
model

DSCNet(
  (ae): AutoEncoder(
    (encoder): Sequential(
      (input): Linear(in_features=1000, out_features=3, bias=True)
      (linear1): Linear(in_features=3, out_features=3, bias=True)
      (relu1): ReLU(inplace=True)
      (linear2): Linear(in_features=3, out_features=5, bias=True)
      (relu2): ReLU(inplace=True)
    )
    (decoder): Sequential(
      (inv-linear1): Linear(in_features=5, out_features=3, bias=True)
      (relud0): ReLU(inplace=True)
      (inv-linear2): Linear(in_features=3, out_features=3, bias=True)
      (relud1): ReLU(inplace=True)
      (output): Linear(in_features=3, out_features=1000, bias=True)
    )
  )
  (self_expression): SelfExpression()
)

In [4]:
# d = pd.read_csv("cryp.csv")
# X = np.array(d["rate"].tolist())
# y= np.array(d["label"].tolist())
# X_train = X[:3500]
# y_train = y[:3500]
# X_test = X[3500:]
# y_test = y[3500:]
# train_data= TimeseriesDataset(X_train,y_train)
# train_present = X_train[3500:]
# test_data= TimeseriesDataset(X_test,y_test)
# # train_dataset = TimeseriesDataset(X_lstm, y_lstm, seq_len=4)
# train_loader = torch.utils.data.DataLoader(train_data, batch_size = 32, shuffle = False)
# test_loader = torch.utils.data.DataLoader(test_data, batch_size = 32, shuffle = False)

In [5]:
inp = torch.randn(NUM_SAMPLES, SEQUENCE_LENGTH)
out = torch.randn(NUM_SAMPLES, SEQUENCE_LENGTH)

In [6]:
model(inp)

(tensor([[-0.5258, -0.2553,  0.1561,  ..., -0.4746, -0.2253, -0.4536],
         [-0.5258, -0.2553,  0.1561,  ..., -0.4746, -0.2253, -0.4536],
         [-0.5258, -0.2553,  0.1561,  ..., -0.4746, -0.2253, -0.4536],
         ...,
         [-0.5258, -0.2553,  0.1561,  ..., -0.4746, -0.2253, -0.4536],
         [-0.5258, -0.2553,  0.1561,  ..., -0.4746, -0.2253, -0.4536],
         [-0.5258, -0.2553,  0.1561,  ..., -0.4746, -0.2253, -0.4536]],
        grad_fn=<AddmmBackward0>),
 tensor([[0.1107, 0.2863, 0.0000, 0.0598, 0.4363],
         [0.1110, 0.0000, 0.0000, 0.0000, 0.1958],
         [0.1107, 0.2863, 0.0000, 0.0598, 0.4363],
         ...,
         [0.1107, 0.2863, 0.0000, 0.0598, 0.4363],
         [0.1110, 0.0000, 0.0000, 0.0000, 0.1914],
         [0.1109, 0.0697, 0.0000, 0.0000, 0.2747]], grad_fn=<ViewBackward0>),
 tensor([[1.5820e-06, 1.8504e-06, 4.8216e-09, 2.3232e-07, 3.9851e-06],
         [1.5820e-06, 1.8504e-06, 4.8216e-09, 2.3232e-07, 3.9851e-06],
         [1.5820e-06, 1.8504e-06, 4

In [7]:
model.self_expression.Coefficient.shape

torch.Size([1320, 1320])

In [8]:
K = 3
alpha=0.04
dim_subspace=12
ro=8
C = model.self_expression.Coefficient.detach().to("cpu").numpy()
y_pred = spectral_clustering(C, K, dim_subspace, alpha, ro)

In [9]:
y_pred.shape

(1320,)

In [10]:
y_pred

array([2, 0, 0, ..., 0, 1, 0])