In [1]:
import torch
import pandas as pd
import numpy as np

from model import DSCNet
from post_clustering import spectral_clustering

In [2]:
NUM_SAMPLES = 1000
NUM_FEATURES = 3

In [3]:
model = DSCNet(channels=[NUM_FEATURES, 3, 3, 5], kernels=[3, 3, 3], num_sample=NUM_SAMPLES)
model

DSCNet(
  (ae): LinearAE(
    (encoder): Sequential(
      (linear1): Linear(in_features=3, out_features=3, bias=True)
      (relu1): ReLU(inplace=True)
      (linear2): Linear(in_features=3, out_features=3, bias=True)
      (relu2): ReLU(inplace=True)
      (linear3): Linear(in_features=3, out_features=5, bias=True)
      (relu3): ReLU(inplace=True)
    )
    (decoder): Sequential(
      (inv-linear1): Linear(in_features=5, out_features=3, bias=True)
      (relud0): ReLU(inplace=True)
      (inv-linear2): Linear(in_features=3, out_features=3, bias=True)
      (relud1): ReLU(inplace=True)
      (inv-linear3): Linear(in_features=3, out_features=3, bias=True)
      (relud2): ReLU(inplace=True)
    )
  )
  (self_expression): SelfExpression()
)

In [4]:
# d = pd.read_csv("cryp.csv")
# X = np.array(d["rate"].tolist())
# y= np.array(d["label"].tolist())
# X_train = X[:3500]
# y_train = y[:3500]
# X_test = X[3500:]
# y_test = y[3500:]
# train_data= TimeseriesDataset(X_train,y_train)
# train_present = X_train[3500:]
# test_data= TimeseriesDataset(X_test,y_test)
# # train_dataset = TimeseriesDataset(X_lstm, y_lstm, seq_len=4)
# train_loader = torch.utils.data.DataLoader(train_data, batch_size = 32, shuffle = False)
# test_loader = torch.utils.data.DataLoader(test_data, batch_size = 32, shuffle = False)

In [5]:
inp = torch.randn(NUM_SAMPLES, NUM_FEATURES)
out = torch.randn(NUM_SAMPLES, NUM_FEATURES)

In [6]:
model(inp)

(tensor([[0.0000, 0.3925, 0.0000],
         [0.0000, 0.3925, 0.0000],
         [0.0000, 0.3925, 0.0000],
         ...,
         [0.0000, 0.3925, 0.0000],
         [0.0000, 0.3925, 0.0000],
         [0.0000, 0.3925, 0.0000]], grad_fn=<ReluBackward0>),
 tensor([[0.0000, 0.1190, 0.0000, 0.5931, 0.1819],
         [0.0000, 0.1510, 0.0000, 0.4988, 0.0282],
         [0.0000, 0.2045, 0.0000, 0.5986, 0.2057],
         ...,
         [0.0000, 0.1693, 0.0000, 0.5328, 0.0886],
         [0.0000, 0.1170, 0.0000, 0.5171, 0.0533],
         [0.0000, 0.1897, 0.0000, 0.5826, 0.1762]], grad_fn=<ViewBackward0>),
 tensor([[0.0000e+00, 1.5517e-06, 0.0000e+00, 5.2877e-06, 7.9492e-07],
         [0.0000e+00, 1.5517e-06, 0.0000e+00, 5.2877e-06, 7.9492e-07],
         [0.0000e+00, 1.5517e-06, 0.0000e+00, 5.2877e-06, 7.9492e-07],
         ...,
         [0.0000e+00, 1.5517e-06, 0.0000e+00, 5.2877e-06, 7.9492e-07],
         [0.0000e+00, 1.5517e-06, 0.0000e+00, 5.2877e-06, 7.9492e-07],
         [0.0000e+00, 1.5517e-06,

In [7]:
model.self_expression.Coefficient.shape

torch.Size([1000, 1000])

In [8]:
K = 2
alpha=0.04
dim_subspace=12
ro=8
C = model.self_expression.Coefficient.detach().to("cpu").numpy()
y_pred = spectral_clustering(C, K, dim_subspace, alpha, ro)

In [10]:
y_pred.shape

(1000,)