In [1]:
import torch
import pandas as pd
import numpy as np

from model import DSCNet

In [2]:
NUM_SAMPLES = 1000
NUM_FEATURES = 3

In [3]:
model = DSCNet(channels=[NUM_FEATURES, 3, 3, 5], kernels=[3, 3, 3], num_sample=NUM_SAMPLES)
model

DSCNet(
  (ae): LinearAE(
    (encoder): Sequential(
      (linear1): Linear(in_features=3, out_features=3, bias=True)
      (relu1): ReLU(inplace=True)
      (linear2): Linear(in_features=3, out_features=3, bias=True)
      (relu2): ReLU(inplace=True)
      (linear3): Linear(in_features=3, out_features=5, bias=True)
      (relu3): ReLU(inplace=True)
    )
    (decoder): Sequential(
      (inv-linear1): Linear(in_features=5, out_features=3, bias=True)
      (relud0): ReLU(inplace=True)
      (inv-linear2): Linear(in_features=3, out_features=3, bias=True)
      (relud1): ReLU(inplace=True)
      (inv-linear3): Linear(in_features=3, out_features=3, bias=True)
      (relud2): ReLU(inplace=True)
    )
  )
  (self_expression): SelfExpression()
)

In [4]:
# d = pd.read_csv("cryp.csv")
# X = np.array(d["rate"].tolist())
# y= np.array(d["label"].tolist())
# X_train = X[:3500]
# y_train = y[:3500]
# X_test = X[3500:]
# y_test = y[3500:]
# train_data= TimeseriesDataset(X_train,y_train)
# train_present = X_train[3500:]
# test_data= TimeseriesDataset(X_test,y_test)
# # train_dataset = TimeseriesDataset(X_lstm, y_lstm, seq_len=4)
# train_loader = torch.utils.data.DataLoader(train_data, batch_size = 32, shuffle = False)
# test_loader = torch.utils.data.DataLoader(test_data, batch_size = 32, shuffle = False)

In [5]:
inp = torch.randn(NUM_SAMPLES, NUM_FEATURES)
out = torch.randn(NUM_SAMPLES, NUM_FEATURES)

In [6]:
model(inp)

(tensor([[0.0000, 0.0000, 0.4953],
         [0.0000, 0.0000, 0.4953],
         [0.0000, 0.0000, 0.4953],
         ...,
         [0.0000, 0.0000, 0.4953],
         [0.0000, 0.0000, 0.4953],
         [0.0000, 0.0000, 0.4953]], grad_fn=<ReluBackward0>),
 tensor([[0.0000, 0.2803, 0.2322, 0.0000, 0.0000],
         [0.0000, 0.2828, 0.2361, 0.0000, 0.0000],
         [0.0000, 0.2946, 0.2547, 0.0000, 0.0000],
         ...,
         [0.0000, 0.3072, 0.2746, 0.0000, 0.0000],
         [0.0000, 0.2840, 0.2381, 0.0000, 0.0000],
         [0.0000, 0.2946, 0.2547, 0.0000, 0.0000]], grad_fn=<ViewBackward0>),
 tensor([[0.0000e+00, 2.9449e-06, 2.5304e-06, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.9449e-06, 2.5304e-06, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.9449e-06, 2.5304e-06, 0.0000e+00, 0.0000e+00],
         ...,
         [0.0000e+00, 2.9449e-06, 2.5304e-06, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.9449e-06, 2.5304e-06, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.9449e-06,